# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-17 00:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sedUI', '0002_auto_20161017_0045'),
    ]

    operations = [
        migrations.AddField(
            model_name='health',
            name='health_condition',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='health',
            name='health_type',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='scout',
            name='affiliation',
            field=models.CharField(blank=True, choices=[(b'BSA', b'Boy Scouts of America'), (b'GSA', b'Girl Scouts of America'), (b'VC', b'Venture Crew')], max_length=4),
        ),
    ]
